---
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    aws_region: eu-central-1
    resource_state: present # absent doesn't work for ordering reasons

  tasks:

  - name: create DMZ VPC
    ec2_vpc_net:
      name: iamshield-DMZ
      cidr_block: 10.1.0.0/16
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
    register: vpc

  - name: Internet Gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
    register: igw

  - name: DMZ VPC network
    ec2_vpc_subnet:
      cidr: 10.1.{{ item.0 }}.0/24
      az: "{{ item.1 }}"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
      tags: {} # crashes when no tags line is defined
    with_indexed_items:
      - "{{ aws_region}}a"
      - "{{ aws_region}}b"
      - "{{ aws_region}}c"
    register: subnets_dmz

  - name: Secure VPC network
    ec2_vpc_subnet:
      cidr: 10.1.{{ item.0 + 100 }}.0/24
      az: "{{ item.1 }}"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
      tags: {} # crashes when no tags line is defined
    with_indexed_items:
      - "{{ aws_region}}a"
      - "{{ aws_region}}b"
      - "{{ aws_region}}c"
    register: subnets_secure

  - name: create user-facing ELB
    ec2_elb_lb:
      name: ELB-DMZ
      region: "{{ aws_region }}"
      subnets:
        - "{{ subnets_dmz.results[0].subnet.id }}"
        - "{{ subnets_dmz.results[1].subnet.id }}"
        - "{{ subnets_dmz.results[2].subnet.id }}"
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      state: "{{ resource_state }}"
      tags: {} # crashes when no tags line is defined

  - name: create secure ELB
    ec2_elb_lb:
      name: ELB-secure
      region: "{{ aws_region }}"
      subnets:
        - "{{ subnets_secure.results[0].subnet.id }}"
        - "{{ subnets_secure.results[1].subnet.id }}"
        - "{{ subnets_secure.results[2].subnet.id }}"
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      state: "{{ resource_state }}"
      tags: {} # crashes when no tags line is defined

  - name: Create proxy instance
    ec2:
      group: default
      image: ami-657bd20a
      instance_type: t2.nano
      vpc_subnet_id: "{{ subnets_dmz.results[0].subnet.id }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
    register: proxy_instance

  - name: Create IAM instance
    ec2:
      group: default
      image: ami-657bd20a
      instance_type: t2.nano
      vpc_subnet_id: "{{ subnets_dmz.results[0].subnet.id }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
    register: iam_instance

  - name: Attach proxy instance to ELB
    ec2_elb:
      ec2_elbs:
        - 'ELB-DMZ'
      instance_id: "{{ proxy_instance.instance_ids[0] }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
      wait: no

  - name: Attach IAM instance to ELB
    ec2_elb:
      ec2_elbs:
        - 'ELB-secure'
      instance_id: "{{ iam_instance.instance_ids[0] }}"
      region: "{{ aws_region }}"
      state: "{{ resource_state }}"
      wait: no
